version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      # - <port on localhost>:<port on container>
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro # ro - readonly
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # to live reload our server after a file change
    env_file:
      - ./.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
